### ISSUE TITLE
[FIX] env: _=がダブってる

### ISSUE THREAD

**Issue by yotsubo4242** [yotsubo4242/mini-shell#25]
```shell
bash$ env
> ...
> VSCODE_IPC_HOOK_CLI=/mnt/wslg/runtime-dir/vscode-ipc-d2891908-5c91-4833-bc10-7bc1a84188cf.sock
> _=/usr/bin/env
```

```shell
mini-shell$ env
> ...
> VSCODE_IPC_HOOK_CLI=/mnt/wslg/runtime-dir/vscode-ipc-d2891908-5c91-4833-bc10-7bc1a84188cf.sock
> _=./minishell
> _=/usr/bin/env
```

**Comment by yotsubo4242** [comment]
[問題]
① 特殊環境変数である＿がminishellでは一般の環境変数と同様に普通に`export`でも見れてしまっている
② ①のせいもあって, `env`で＿＝が二つ表示されてしまっている

[実装方針]
1. minishellの`envmap`を作成するタイミングでkeyが＿になっているものを削除しておく
2. `builtin_env()`の最後に`ft_printf()` で無理やり＿＝を出力する

**Comment by tor-ato** [comment]
実装みました！
mini-shell$ envの場合、envを最後に実行してるから、
毎回必ず
```
_=/usr/bin/env
```
が出力されてる認識であってるかな？
で 
"_" は "_"でで設定されてしまうから、それを無理やりアンセットしてるってことよね
上記認識で、実装には問題なさそうなので、一旦マージします！

**Comment by tor-ato** [comment]
printenv _ でボロが出る可能性あり
