### ISSUE TITLE
[FEAT] CLEAN UP

### ISSUE THREAD

**Issue by tor-ato** [yotsubo4242/mini-shell#69]
バカデカ構造体を全部フリーするんじゃ！

**Comment by tor-ato** [comment]
fd クローズし忘れチェック

**Comment by yotsubo4242** [comment]
leaksは一旦目に付くところはなさそうなので, とりあえずfd close忘れの確認とそのcleanupを実装

**Comment by yotsubo4242** [comment]
issue #109 
issue #110 
に切り分けたのでこれはcloseしときます！
