### ISSUE TITLE
[FIX] env empty string key ("")

### ISSUE THREAD

**Issue by tor-ato** [yotsubo4242/mini-shell#87]
### 概要
exportで空文字をvalueとしてsetした場合、envはkye+=を出力
exportでvalueをsetしなかった場合、envは何も出力しない
### 前提
exportは=をつけないでkeyをsetすると、valueに何もセットされない
=をつけてsetした場合、空文字がsetされる
```
export a1 a2=
export 
declare -x a1
declare -x a2=""

env | grep a1

env | grep a2
a2=
```

**Comment by yotsubo4242** [comment]
今までのissue消化で済んでた問題でした.
テストケースの追加だけします.
